name: pagespeed metrics
on:
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Succinct report
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.pagespeed.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEEDMETRIC }}
          plugin_pagespeed_url: https://silvestristefano.github.io
