name: pagespeed metrics
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Succinct report
        uses: lowlighter/metrics@latest
        with:
          filename: pagespeed.svg
          token: ${{ secrets.METRIC_TOKEN }}
          base: ""
          template: classic
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://silvestristefano.github.io
